revoke delete on table "public"."User" from "anon";

revoke insert on table "public"."User" from "anon";

revoke references on table "public"."User" from "anon";

revoke select on table "public"."User" from "anon";

revoke trigger on table "public"."User" from "anon";

revoke truncate on table "public"."User" from "anon";

revoke update on table "public"."User" from "anon";

revoke delete on table "public"."User" from "authenticated";

revoke insert on table "public"."User" from "authenticated";

revoke references on table "public"."User" from "authenticated";

revoke select on table "public"."User" from "authenticated";

revoke trigger on table "public"."User" from "authenticated";

revoke truncate on table "public"."User" from "authenticated";

revoke update on table "public"."User" from "authenticated";

revoke delete on table "public"."User" from "service_role";

revoke insert on table "public"."User" from "service_role";

revoke references on table "public"."User" from "service_role";

revoke select on table "public"."User" from "service_role";

revoke trigger on table "public"."User" from "service_role";

revoke truncate on table "public"."User" from "service_role";

revoke update on table "public"."User" from "service_role";

revoke delete on table "public"."employees" from "anon";

revoke insert on table "public"."employees" from "anon";

revoke references on table "public"."employees" from "anon";

revoke select on table "public"."employees" from "anon";

revoke trigger on table "public"."employees" from "anon";

revoke truncate on table "public"."employees" from "anon";

revoke update on table "public"."employees" from "anon";

revoke delete on table "public"."employees" from "authenticated";

revoke insert on table "public"."employees" from "authenticated";

revoke references on table "public"."employees" from "authenticated";

revoke select on table "public"."employees" from "authenticated";

revoke trigger on table "public"."employees" from "authenticated";

revoke truncate on table "public"."employees" from "authenticated";

revoke update on table "public"."employees" from "authenticated";

revoke delete on table "public"."employees" from "service_role";

revoke insert on table "public"."employees" from "service_role";

revoke references on table "public"."employees" from "service_role";

revoke select on table "public"."employees" from "service_role";

revoke trigger on table "public"."employees" from "service_role";

revoke truncate on table "public"."employees" from "service_role";

revoke update on table "public"."employees" from "service_role";

alter table "public"."User" drop constraint "User_pkey";

alter table "public"."employees" drop constraint "employees_pkey";

alter table "public"."events" drop constraint "event_pkey";

drop index if exists "public"."User_pkey";

drop index if exists "public"."employees_pkey";

drop index if exists "public"."event_pkey";

drop table "public"."User";

drop table "public"."employees";


  create table "public"."daily_steps" (
    "id" bigint generated by default as identity not null,
    "profile_id" uuid,
    "event_id" uuid,
    "dailysteps" bigint,
    "stepdate" date
      );


alter table "public"."daily_steps" enable row level security;


  create table "public"."leaderboard" (
    "event_id" uuid not null,
    "step_count" integer default 0,
    "rank" integer,
    "updated_at" timestamp without time zone default now()
      );



  create table "public"."profiles" (
    "date_created" timestamp without time zone default now(),
    "email" character varying not null,
    "profile_id" uuid not null,
    "total_steps" integer,
    "role" smallint,
    "organization" text
      );


alter table "public"."profiles" enable row level security;

alter table "public"."events" drop column "id";

alter table "public"."events" add column "date_created" timestamp without time zone default now();

alter table "public"."events" add column "event_id" uuid not null default gen_random_uuid();

alter table "public"."events" add column "is_published" boolean not null;

alter table "public"."events" alter column "event_name" set not null;

alter table "public"."events" alter column "is_private" drop default;

alter table "public"."events" alter column "start_date" set not null;

CREATE UNIQUE INDEX daily_steps_pkey ON public.daily_steps USING btree (id);

CREATE UNIQUE INDEX events_pkey ON public.events USING btree (event_id);

CREATE UNIQUE INDEX profiles_email_key ON public.profiles USING btree (email);

CREATE UNIQUE INDEX profiles_pkey ON public.profiles USING btree (profile_id);

alter table "public"."daily_steps" add constraint "daily_steps_pkey" PRIMARY KEY using index "daily_steps_pkey";

alter table "public"."events" add constraint "events_pkey" PRIMARY KEY using index "events_pkey";

alter table "public"."profiles" add constraint "profiles_pkey" PRIMARY KEY using index "profiles_pkey";

alter table "public"."daily_steps" add constraint "daily_steps_event_id_fkey" FOREIGN KEY (event_id) REFERENCES public.events(event_id) not valid;

alter table "public"."daily_steps" validate constraint "daily_steps_event_id_fkey";

alter table "public"."daily_steps" add constraint "daily_steps_profile_id_fkey" FOREIGN KEY (profile_id) REFERENCES public.profiles(profile_id) not valid;

alter table "public"."daily_steps" validate constraint "daily_steps_profile_id_fkey";

alter table "public"."leaderboard" add constraint "leaderboard_event_id_fkey" FOREIGN KEY (event_id) REFERENCES public.events(event_id) ON DELETE CASCADE not valid;

alter table "public"."leaderboard" validate constraint "leaderboard_event_id_fkey";

alter table "public"."profiles" add constraint "profiles_email_key" UNIQUE using index "profiles_email_key";

alter table "public"."profiles" add constraint "profiles_profile_id_fkey" FOREIGN KEY (profile_id) REFERENCES auth.users(id) not valid;

alter table "public"."profiles" validate constraint "profiles_profile_id_fkey";

alter table "public"."profiles" add constraint "profiles_total_steps_check" CHECK ((total_steps > 0)) not valid;

alter table "public"."profiles" validate constraint "profiles_total_steps_check";

set check_function_bodies = off;

create or replace view "public"."event_step_totals" as  SELECT profiles.profile_id,
    daily_steps.event_id,
    (daily_steps.dailysteps + profiles.total_steps) AS summed_steps
   FROM public.daily_steps,
    public.profiles;


CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
  INSERT INTO public.profiles (id, email)
  VALUES (NEW.id, NEW.email);
  RETURN NEW;
END;
$function$
;

grant delete on table "public"."daily_steps" to "anon";

grant insert on table "public"."daily_steps" to "anon";

grant references on table "public"."daily_steps" to "anon";

grant select on table "public"."daily_steps" to "anon";

grant trigger on table "public"."daily_steps" to "anon";

grant truncate on table "public"."daily_steps" to "anon";

grant update on table "public"."daily_steps" to "anon";

grant delete on table "public"."daily_steps" to "authenticated";

grant insert on table "public"."daily_steps" to "authenticated";

grant references on table "public"."daily_steps" to "authenticated";

grant select on table "public"."daily_steps" to "authenticated";

grant trigger on table "public"."daily_steps" to "authenticated";

grant truncate on table "public"."daily_steps" to "authenticated";

grant update on table "public"."daily_steps" to "authenticated";

grant delete on table "public"."daily_steps" to "service_role";

grant insert on table "public"."daily_steps" to "service_role";

grant references on table "public"."daily_steps" to "service_role";

grant select on table "public"."daily_steps" to "service_role";

grant trigger on table "public"."daily_steps" to "service_role";

grant truncate on table "public"."daily_steps" to "service_role";

grant update on table "public"."daily_steps" to "service_role";

grant delete on table "public"."leaderboard" to "anon";

grant insert on table "public"."leaderboard" to "anon";

grant references on table "public"."leaderboard" to "anon";

grant select on table "public"."leaderboard" to "anon";

grant trigger on table "public"."leaderboard" to "anon";

grant truncate on table "public"."leaderboard" to "anon";

grant update on table "public"."leaderboard" to "anon";

grant delete on table "public"."leaderboard" to "authenticated";

grant insert on table "public"."leaderboard" to "authenticated";

grant references on table "public"."leaderboard" to "authenticated";

grant select on table "public"."leaderboard" to "authenticated";

grant trigger on table "public"."leaderboard" to "authenticated";

grant truncate on table "public"."leaderboard" to "authenticated";

grant update on table "public"."leaderboard" to "authenticated";

grant delete on table "public"."leaderboard" to "service_role";

grant insert on table "public"."leaderboard" to "service_role";

grant references on table "public"."leaderboard" to "service_role";

grant select on table "public"."leaderboard" to "service_role";

grant trigger on table "public"."leaderboard" to "service_role";

grant truncate on table "public"."leaderboard" to "service_role";

grant update on table "public"."leaderboard" to "service_role";

grant delete on table "public"."profiles" to "anon";

grant insert on table "public"."profiles" to "anon";

grant references on table "public"."profiles" to "anon";

grant select on table "public"."profiles" to "anon";

grant trigger on table "public"."profiles" to "anon";

grant truncate on table "public"."profiles" to "anon";

grant update on table "public"."profiles" to "anon";

grant delete on table "public"."profiles" to "authenticated";

grant insert on table "public"."profiles" to "authenticated";

grant references on table "public"."profiles" to "authenticated";

grant select on table "public"."profiles" to "authenticated";

grant trigger on table "public"."profiles" to "authenticated";

grant truncate on table "public"."profiles" to "authenticated";

grant update on table "public"."profiles" to "authenticated";

grant delete on table "public"."profiles" to "service_role";

grant insert on table "public"."profiles" to "service_role";

grant references on table "public"."profiles" to "service_role";

grant select on table "public"."profiles" to "service_role";

grant trigger on table "public"."profiles" to "service_role";

grant truncate on table "public"."profiles" to "service_role";

grant update on table "public"."profiles" to "service_role";


  create policy "Users can update their own profile."
  on "public"."profiles"
  as permissive
  for update
  to public
using ((auth.uid() = profile_id));



  create policy "Users can view their own profile."
  on "public"."profiles"
  as permissive
  for select
  to public
using ((auth.uid() = profile_id));


CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();


