
  create table "public"."teams" (
    "id" bigint generated by default as identity not null,
    "size" bigint not null,
    "name" text,
    "event_id" uuid
      );


alter table "public"."teams" enable row level security;


  create table "public"."tiers" (
    "id" bigint generated by default as identity not null,
    "benchmarks" bigint[],
    "num_tiers" bigint,
    "event_id" uuid not null
      );


alter table "public"."events" add column "banner_url" text;

alter table "public"."events" alter column "is_published" set default false;

alter table "public"."profiles" add column "team_id" bigint;

alter table "public"."profiles" add column "username" text;

CREATE UNIQUE INDEX events_banner_url_key ON public.events USING btree (banner_url);

CREATE UNIQUE INDEX teams_pkey ON public.teams USING btree (id);

CREATE UNIQUE INDEX tiers_pkey ON public.tiers USING btree (id);

alter table "public"."teams" add constraint "teams_pkey" PRIMARY KEY using index "teams_pkey";

alter table "public"."tiers" add constraint "tiers_pkey" PRIMARY KEY using index "tiers_pkey";

alter table "public"."events" add constraint "events_banner_url_key" UNIQUE using index "events_banner_url_key";

alter table "public"."profiles" add constraint "profiles_team_id_fkey" FOREIGN KEY (team_id) REFERENCES public.teams(id) not valid;

alter table "public"."profiles" validate constraint "profiles_team_id_fkey";

alter table "public"."teams" add constraint "teams_event_id_fkey" FOREIGN KEY (event_id) REFERENCES public.events(event_id) not valid;

alter table "public"."teams" validate constraint "teams_event_id_fkey";

alter table "public"."tiers" add constraint "tiers_event_id_fkey" FOREIGN KEY (event_id) REFERENCES public.events(event_id) not valid;

alter table "public"."tiers" validate constraint "tiers_event_id_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.assign_tier_after_leaderboard_update()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
DECLARE
    new_tier TEXT;
BEGIN
    SELECT tier_name INTO new_tier
    FROM tiers
    WHERE NEW.total_steps >= min_steps
    ORDER BY min_steps DESC
    LIMIT 1;

    UPDATE profiles
    SET tier_name = new_tier
    WHERE profile_id = NEW.profile_id;

    RETURN NEW;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.update_leaderboard_after_daily_steps()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
    INSERT INTO leaderboard (profile_id, total_steps, last_updated)
    VALUES (NEW.profile_id, NEW.steps, NOW())
    ON CONFLICT (profile_id) DO UPDATE
        SET total_steps = leaderboard.total_steps + EXCLUDED.total_steps,
            last_updated = NOW();
    RETURN NEW;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.validate_daily_steps()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
    IF NEW.steps < 0 OR NEW.steps > 100000 THEN
        RAISE EXCEPTION 'Invalid step count: %', NEW.steps;
    END IF;
    RETURN NEW;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$BEGIN
  INSERT INTO public.profiles (profile_id, email)
  VALUES (NEW.id, NEW.email);
  RETURN NEW;
END;$function$
;

grant delete on table "public"."teams" to "anon";

grant insert on table "public"."teams" to "anon";

grant references on table "public"."teams" to "anon";

grant select on table "public"."teams" to "anon";

grant trigger on table "public"."teams" to "anon";

grant truncate on table "public"."teams" to "anon";

grant update on table "public"."teams" to "anon";

grant delete on table "public"."teams" to "authenticated";

grant insert on table "public"."teams" to "authenticated";

grant references on table "public"."teams" to "authenticated";

grant select on table "public"."teams" to "authenticated";

grant trigger on table "public"."teams" to "authenticated";

grant truncate on table "public"."teams" to "authenticated";

grant update on table "public"."teams" to "authenticated";

grant delete on table "public"."teams" to "service_role";

grant insert on table "public"."teams" to "service_role";

grant references on table "public"."teams" to "service_role";

grant select on table "public"."teams" to "service_role";

grant trigger on table "public"."teams" to "service_role";

grant truncate on table "public"."teams" to "service_role";

grant update on table "public"."teams" to "service_role";

grant delete on table "public"."tiers" to "anon";

grant insert on table "public"."tiers" to "anon";

grant references on table "public"."tiers" to "anon";

grant select on table "public"."tiers" to "anon";

grant trigger on table "public"."tiers" to "anon";

grant truncate on table "public"."tiers" to "anon";

grant update on table "public"."tiers" to "anon";

grant delete on table "public"."tiers" to "authenticated";

grant insert on table "public"."tiers" to "authenticated";

grant references on table "public"."tiers" to "authenticated";

grant select on table "public"."tiers" to "authenticated";

grant trigger on table "public"."tiers" to "authenticated";

grant truncate on table "public"."tiers" to "authenticated";

grant update on table "public"."tiers" to "authenticated";

grant delete on table "public"."tiers" to "service_role";

grant insert on table "public"."tiers" to "service_role";

grant references on table "public"."tiers" to "service_role";

grant select on table "public"."tiers" to "service_role";

grant trigger on table "public"."tiers" to "service_role";

grant truncate on table "public"."tiers" to "service_role";

grant update on table "public"."tiers" to "service_role";

CREATE TRIGGER trg_validate_daily_steps BEFORE INSERT ON public.daily_steps FOR EACH ROW EXECUTE FUNCTION public.validate_daily_steps();

CREATE TRIGGER trg_assign_tier_after_leaderboard_update AFTER UPDATE ON public.leaderboard FOR EACH ROW EXECUTE FUNCTION public.assign_tier_after_leaderboard_update();


